### ISSUE TITLE
X52 Axis inverted

### ISSUE THREAD

**Issue by brittz** [mdjarv/JoystickVisualizer#17]
Hi, i've tested last release Version 0.9.18 and the throttle axes is inverted for X52. 

It is nice to see the 3d model for X52, thank you for that! Another thing; I have X52, Saitek Yoke and Saitek Quadrant, and would be really nice to see Saitek Yoke working too.

Thanks.

**Comment by mdjarv** [comment]
X52 axis has been fixed in later versions

I have considered making a model for a yoke as well, it's on my list of "things to do" :)
