### ISSUE TITLE
Can you add the "Thrustmaster Flight Stick X" ? 

### ISSUE THREAD

**Issue by TheResCo** [mdjarv/JoystickVisualizer#18]
I hope you can add it :) Thanks alot mate :)

**Comment by mdjarv** [comment]
Sorry for the late response, I'll add it to the list of "Sticks to do"

**Comment by mdjarv** [comment]
I'm currently working on the Thrustmaster Rudder Pedals, however if you want to use an existing 3D model we can get that set up in probably less than an hour.

If you can, join the Discord channel found in the description and I'll set you up:
https://github.com/mdjarv/JoystickVisualizer/blob/master/README.md

**Comment by TheResCo** [comment]
Okay. No Problem.

**Comment by mdjarv** [comment]
Added in v0.10.6
