### ISSUE TITLE
Logitech Extreme 3D Pro Slider

### ISSUE THREAD

**Issue by srykho22** [mdjarv/JoystickVisualizer#20]
Hello!
I have just downloaded v0.11.0, and the slider on my Logitech Extreme 3D Pro is does not move in the visualizer. JoystickProxy recognizes the slider, and the values change when I move the slider, so this could be a problem with the model. I use the slider for throttle, so it is important to me that it is modeled. 
Thanks!

**Comment by mdjarv** [comment]
It has not been rigged up in Unity yet, could you check in the proxy window what input name and value shows when the throttle is all the way back, and all the way forwards

**Comment by mdjarv** [comment]
![image](https://user-images.githubusercontent.com/439045/38456368-65358258-3a84-11e8-864e-73faa7ad4bb0.png)

For example in this image, when I pull my friction lever all the way back on my thrustmaster throttle it shows Sliders0 = 65535

**Comment by srykho22** [comment]
When it's all the way back
![capture](https://user-images.githubusercontent.com/31467287/38477039-4b450782-3be3-11e8-9b03-6a399c6df549.PNG)

When it's all the way forward
![capture](https://user-images.githubusercontent.com/31467287/38477092-8233a32a-3be3-11e8-9f40-504af4eba8bb.PNG)

**Comment by srykho22** [comment]
Also, this is the part that should be animated
![capture](https://user-images.githubusercontent.com/31467287/38477138-bf338e66-3be3-11e8-9a4e-671cc2416601.PNG)

**Comment by mdjarv** [comment]
Excellent, that's all I need.

I'll add it and publish an update when I get home from work today

**Comment by mdjarv** [comment]
Fix released in v0.11.2

https://github.com/mdjarv/JoystickVisualizer/releases/tag/v0.11.2
