### ISSUE TITLE
Inverted Axis

### ISSUE THREAD

**Issue by srykho22** [mdjarv/JoystickVisualizer#22]
Hello!
I have just downloaded v0.11.2, and the slider on the Logitech Extreme 3D Pro is inverted. It should be all the way down when the value is 65535, and all the way up when the value is 0.
Thanks!

**Comment by mdjarv** [comment]
Inverted the axis in 0.11.3, let me know if it's ok now

https://github.com/mdjarv/JoystickVisualizer/releases/tag/v0.11.3

**Comment by srykho22** [comment]
It works. Thanks!

**Comment by mdjarv** [comment]
Great :)
