### ISSUE TITLE
JoystickProxy Not Responding

### ISSUE THREAD

**Issue by srykho22** [mdjarv/JoystickVisualizer#24]
Hello!
Occasionally, when I open JoystickProxy, the window opens, but the values don't change when I move the Joystick. When I click the window, the application doesn't respond, starts responding but no values change, then stops responding less than a second later. This issue has occurred since v0.11.2, and still happens to me with v0.11.4

**Comment by mdjarv** [comment]
Which was the last working version you used? 0.11.1?

**Comment by srykho22** [comment]
The last version that was working was 0.11.3, however the problem occasionally happened before. It is only with 0.11.4 that it always happens

**Comment by mdjarv** [comment]
I've looked through the changes made and the prime suspect would be that something on your computer is having issues with the Proxy sending UDP packets on port 11028 (the port was switched from 11011 in 0.11.4)

Could it be some local service or application you're running, or possibly a firewall?

**Comment by mdjarv** [comment]
In 0.11.5 I've changed the UDP port to 11038, so please try it and let me know how it works

https://github.com/mdjarv/JoystickVisualizer/releases/tag/v0.11.5

**Comment by srykho22** [comment]
I updated to 0.11.5, and the app is working. Thanks a lot!

**Comment by mdjarv** [comment]
good to hear... I should probably make the port configurable so it doesn't require a new release if there is a port collision
