### ISSUE TITLE
External Viewer option?

### ISSUE THREAD

**Issue by SnorreSelmer** [mdjarv/JoystickVisualizer#7]
For people who run a separate streaming PC, the visualizer needs to connect to an external IP for data from the proxy. Could this be added?

**Comment by mdjarv** [comment]
What a neat idea, as the proxy and stick already communicate over a network socket it should hopefully be an easy fix. I'll see if I can find the time to look it over

**Comment by SnorreSelmer** [comment]
That would be awesome!

**Comment by mdjarv** [comment]
I've gotten part of the way, functionally it works but the UI needs some tender love and care. Getting some annoying window-freezes if trying to connect to an unavailable host but I should hopefully have a new version out in a day or two

**Comment by mdjarv** [comment]
@SnorreSelmer Release 0.4 is up with a rough draft of what you were asking for, please let me know if it solves your problem :)

https://github.com/mdjarv/JoystickVisualizer/releases/tag/v0.4-alpha

**Comment by SnorreSelmer** [comment]
I've used it a fair bit, seems solid. I think you can close this one.

**Comment by mdjarv** [comment]
Thanks for the feedback, I didn't exeperience any problems with it either so I'm closing this issue. The UI could definitely be improved though but that will be for another time
